### ISSUE TITLE
update JQuery

### ISSUE THREAD

**Issue by cappert** [lyonrb/railsgirly#25]
was: `Uncaught Error: Bootstrap's JavaScript requires jQuery`
## TODO:
- [ ] put JQuery before bootstrap.js
- [x] host the assets on a CDN (https://www.bootstrapcdn.com/), preferably using subresource integrity.
- [x] _We don't actually need javascript on the website at all. (fixed 62ace84)_
- [ ] Bootstrap [3.3.7 is out](https://blog.getbootstrap.com/2016/07/25/bootstrap-3-3-7-released/), which supports JQuery 3, which claims to be slimmer and faster. Review and evaluate. Take a look at [Browser support](https://jquery.com/upgrade-guide/3.0/#browser-support).

**Comment by cappert** [comment]
d620dd5f509ab3cd4c21985c15e693f618034d7c removed bootstrap JS and vendored JQuery.
